version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fin_db
  
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./warehouse/create_warehouse_table.sql:/docker-entrypoint-initdb.d/create_warehouse_table.sql

volumes:
  postgres_data:
